### ISSUE TITLE
identify and extract "registry" based meta data into YAML databases

### ISSUE THREAD

**Issue by wwlwpd** [jasonfleming/asgs#366]
`config/mesh_defaults.sh` and much of `platforms.sh` should be stored as YAML files, e.g.,

```
   "ec95d"|"EC95d")
      #   
      INPUTDIR=$SCRIPTDIR/input/meshes/ec95d
      GRIDFILE=ec_95d.grd   # mesh (fort.14) file
      MESHPROPERTIES=${GRIDFILE}.properties
      CONTROLTEMPLATE=ec_95_fort.15_template   # fort.15 template
      # wind at 10m fort.15 template
      CONTROLTEMPLATENOROUGH=ec_95_nowindreduction.fort.15_template
      CONTROLPROPERTIES=${CONTROLTEMPLATE}.properties
      ELEVSTATIONS=cera_stations.txt
      VELSTATIONS=cera_stations.txt
      METSTATIONS=cera_stations.txt
      NAFILE=null
      NAPROPERTIES=${NAFILE}.properties
      SWANTEMPLATE=fort.26.nolimiter.template   # only used if WAVES=on
      RIVERINIT=null                            # this mesh has no rivers ...
      RIVERFLUX=null
      HINDCASTRIVERFLUX=null
      # interaction between mesh and models:
      TIMESTEPSIZE=30.0           # adcirc time step size (seconds)
      SWANDT=1200                # swan timestep / coupling interval (seconds)
      # intersection between mesh, models, hpc platform, and number of compute cores:
      HINDCASTWALLTIME="06:00:00" # hindcast wall clock time
      ADCPREPWALLTIME="01:00:00"  # adcprep wall clock time, including partmesh
      NOWCASTWALLTIME="01:00:00"  # longest nowcast wall clock time
      FORECASTWALLTIME="01:00:00" # forecast wall clock time
      # FIXME: no unit offset url
      ;;
```
 could be presented as:

```
---
grids:
     - grid: ec95d
         gridnames:
           - ec95d
           - EC95d
        INPUTDIR: input/meshes/ec95d
        GRIDFILE: ec_95d.grd
        MESHPROPERTIESEXT: .properties
        CONTROLTEMPLATE: ec_95_fort.15_template
        CONTROLTEMPLATENOROUGH: ec_95_nowindreduction.fort.15_template
        CONTROLPROPERTIESEXT: .properties
        ELEVSTATIONS: cera_stations.txt
        VELSTATIONS: cera_stations.txt
        METSTATIONS: cera_stations.txt
        NAFILE: ~
        NAPROPERTIESEXT: .properties
        SWANTEMPLATE: fort.26.nolimiter.template
        RIVERINIT: ~
        RIVERFLUX: ~
        HINDCASTRIVERFLUX: ~
        TIMESTEPSIZE: 30.0
        SWANDT: 1200
        HINDCASTWALLTIME: 06:00:00
        ADCPREPWALLTIME: 01:00:00
        NOWCASTWALLTIME: 01:00:00
        FORECASTWALLTIME: 01:00:00
```
